### ISSUE TITLE
Crash Bandicoot runs too fast

### ISSUE THREAD

**Issue by hercc82** [grumpycoders/pcsx-redux#526]
System:
Windows 10, up to date
GTX 960
pcsx-redux 4470.20210615.8.x64
pcsx-redux uses default settings

Issue:
Crash Bandicoot runs very fast. In my opinion 3-4x faster than normal.

Do I need to set something special? Or maybe pure bug?

**Comment by nicolasnoble** [comment]
Try activating FPS limit in the GPU options? Same as #390 I guess.

**Comment by hercc82** [comment]
> Try activating FPS limit in the GPU options? Same as #390 I guess.

Thanks, it works for me. 

BTW the FPS limit is not saved after restarting the application. Bug or feature?

Another point, is there anything wrong with setting this option as default?

**Comment by lorn10** [comment]
Just for reference, I can confirm that the `UseFrameLimit` option is not saved (when set) at the Windows builds (under Wine) and also not at the native Linux builds. This seems to be true also for the `UseFrameSkip` option.

So this looks also for me like some kind of a bug. Or should this be the normal behavior? I don't think so...

**Comment by wheremyfoodat** [comment]
@lorn10 Thanks for your report!
This bug has now been investigated and fixed in a separate branch of pcsx-redux, albeit it might be a while until it's merged upstream.

**Comment by wheremyfoodat** [comment]
@lorn10 This fix is now on the main branch

**Comment by lorn10** [comment]
@wheremyfoodat Unfortunately this issue is still present at Linux build **be742b08**. So when set the option is not saved.

**Comment by wheremyfoodat** [comment]
@lorn10 Can you try again? I just did it (albeit on Windows) and the serialization code shouldn't have anything platform-dependent.
Also are you building main from source or downloading the AppImage builds?

**Comment by lorn10** [comment]
I use the AppImage build, - still not building anything (sorry I am too lazy and the AppImage works despite that really almost perfectly.)

Have again tested it, and when I close PCSX-Redux and start it again, the GPU changes are not saved. This is true for all three options, `Use framelimit`, `Use frameskip` and `SSSPSXLimit`. So this means the first two are after a new startup off while the third option is always enabled.

**Comment by wheremyfoodat** [comment]
@lorn10 Don't sweat it, using the AppImage build is fine.
Can you try nuking pcsx.json (or temporarily moving it to another directory) and check if the GPU settings start working as they should?
If that doesn't work and you don't mind, could you please share your pcsx.json?

**Comment by lorn10** [comment]
**It works now!** I have just to start PCSX-Redux with **root** permissions. `sudo ./PCSX-Redux-HEAD-x86_64.AppImage`

The direct editing of `pcsx.json` also works. When I have done this, the Kate text editor told me that root permissions are necessary for any change. So this then effectively solved the topic. Thanks! :+1:

**Comment by nicolasnoble** [comment]
> The direct editing of `pcsx.json` also works. When I have done this, the Kate text editor told me that root permissions are necessary for any change. So this then effectively solved the topic. Thanks!

This means you've edited / created this file once as root. Fix its permissions.

https://www.geeksforgeeks.org/chown-command-in-linux-with-examples/

**Comment by lorn10** [comment]
Exactly, it was ultimately my fault. Because the AppImage was ans is not directly "launchable" from KDE / Dolphin, I started it the first time from terminal with root permissions. And therefore the `pcsx.json` got itself root rights.

This is a typical Linux beginner issue. Also here, a corresponding short note would be helpful: 

**Linux beginners, DO NOT not start the PCSX-Redux-HEAD-x86_64.AppImage with root rights (sudo)!**

**Comment by wheremyfoodat** [comment]
Glad to see that fixed. Yeah, avoid running anything with sudo unless you need to.

**Comment by nicolasnoble** [comment]
Proper FPS limit is in #587.
